export const SEQUELIZE_TOKEN = Symbol('SEQUELIZE');
export const REDIS_CLIENT_TOKEN = Symbol('REDIS_CLIENT');
export const SEQUILIZE_ACCOUNT_REPO_TOKEN = Symbol('ACCOUNT_PROVIDER');
export const SEQUILIZE_REFRESH_TOKEN_REPO = Symbol(
  'SEQUILIZE_REFRESH_TOKEN_REPO',
);
export const SEQUILIZE_PLAN_REPO_TOKEN = Symbol('SEQUILIZE_PLAN_REPO');
export const SEQUILIZE_SUBSCRIPTION_REPO_TOKEN = Symbol(
  'SEQUILIZE_SUBSCRIPTION_REPO_TOKEN',
);
export const SEQUILIZE_SUBSCRIPTION_TOKEN_REPO_TOKEN =
  'SEQUILIZE_SUBSCRIPTION_TOKEN_REPO_TOKEN';
